2023-11-20 17:22:42.682121: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/mnt/local/cuda/lib64:/mnt/local/petsc/lib:/mnt/local/cuba/lib:/usr/lib64/cernlib/2006-g77/lib:/mnt/local/gromacs/lib64:/mnt/local/cuda/lib64:/mnt/local/petsc/lib:/mnt/local/cuba/lib:/usr/lib64/cernlib/2006-g77/lib:/mnt/local/gromacs/lib64
2023-11-20 17:22:42.682655: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
Traceback (most recent call last):
  File "/mnt/research/d.byrd/students/rdasgupt/poker-goat/game/pokerGame.py", line 191, in <module>
    main(sys.argv[1])
  File "/mnt/research/d.byrd/students/rdasgupt/poker-goat/game/pokerGame.py", line 182, in main
    PokerGame(
  File "/mnt/research/d.byrd/students/rdasgupt/poker-goat/game/pokerGame.py", line 32, in __init__
    self.model.trainModel()
  File "/mnt/research/d.byrd/students/rdasgupt/poker-goat/game/model.py", line 103, in trainModel
    from model_tester import test_model
  File "/mnt/research/d.byrd/students/rdasgupt/poker-goat/game/model_tester.py", line 24, in <module>
    model = Model(load_model=True)
  File "/mnt/research/d.byrd/students/rdasgupt/poker-goat/game/model.py", line 12, in __init__
    self.model = self.loadModelFromFile()
  File "/mnt/research/d.byrd/students/rdasgupt/poker-goat/game/model.py", line 63, in loadModelFromFile
    largest_model_file = model_files[29]
IndexError: list index out of range
